# Form implementation generated from reading ui file 'picard-plugin-search-engine-lookup/options_search_engine_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_SearchEngineEditorDialog(object):
    def setupUi(self, SearchEngineEditorDialog):
        SearchEngineEditorDialog.setObjectName("SearchEngineEditorDialog")
        SearchEngineEditorDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        SearchEngineEditorDialog.resize(560, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchEngineEditorDialog.sizePolicy().hasHeightForWidth())
        SearchEngineEditorDialog.setSizePolicy(sizePolicy)
        SearchEngineEditorDialog.setMinimumSize(QtCore.QSize(560, 200))
        SearchEngineEditorDialog.setMaximumSize(QtCore.QSize(560, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchEngineEditorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description = QtWidgets.QLabel(parent=SearchEngineEditorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(0, 10))
        self.description.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.description.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(parent=SearchEngineEditorDialog)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.label_url = QtWidgets.QLabel(parent=SearchEngineEditorDialog)
        self.label_url.setObjectName("label_url")
        self.gridLayout.addWidget(self.label_url, 1, 0, 1, 1)
        self.le_title = QtWidgets.QLineEdit(parent=SearchEngineEditorDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_title.setFont(font)
        self.le_title.setToolTipDuration(-1)
        self.le_title.setObjectName("le_title")
        self.gridLayout.addWidget(self.le_title, 0, 1, 1, 1)
        self.le_url = QtWidgets.QLineEdit(parent=SearchEngineEditorDialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.le_url.setFont(font)
        self.le_url.setObjectName("le_url")
        self.gridLayout.addWidget(self.le_url, 1, 1, 1, 1)
        self.img_valid_title = QtWidgets.QLabel(parent=SearchEngineEditorDialog)
        self.img_valid_title.setMinimumSize(QtCore.QSize(16, 16))
        self.img_valid_title.setText("")
        self.img_valid_title.setObjectName("img_valid_title")
        self.gridLayout.addWidget(self.img_valid_title, 0, 2, 1, 1)
        self.img_valid_url = QtWidgets.QLabel(parent=SearchEngineEditorDialog)
        self.img_valid_url.setMinimumSize(QtCore.QSize(16, 16))
        self.img_valid_url.setText("")
        self.img_valid_url.setObjectName("img_valid_url")
        self.gridLayout.addWidget(self.img_valid_url, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SearchEngineEditorDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SearchEngineEditorDialog)
        QtCore.QMetaObject.connectSlotsByName(SearchEngineEditorDialog)

    def retranslateUi(self, SearchEngineEditorDialog):
        _translate = QtCore.QCoreApplication.translate
        SearchEngineEditorDialog.setWindowTitle(_translate("SearchEngineEditorDialog", "window.title"))
        self.description.setText(_translate("SearchEngineEditorDialog", "label.description"))
        self.label_title.setText(_translate("SearchEngineEditorDialog", "label.title"))
        self.label_url.setText(_translate("SearchEngineEditorDialog", "label.url"))
        self.le_title.setToolTip(_translate("SearchEngineEditorDialog", "The title to show in the list for the search engine provider"))
        self.le_url.setToolTip(_translate("SearchEngineEditorDialog", "The URL to use for the search engine provider"))
